### ISSUE TITLE
Add a Readme

### ISSUE THREAD

**Issue by namitdoshi** [namitdoshi/car-damage-detective-web#2]
A good well structured Readme containing all the information of the project and its features would be appreciated. Thanks <3

**Comment by ultrinnan** [comment]
Hello @namitdoshi , I can do it :) Please assign me to this issue. 
Regards

**Comment by namitdoshi** [comment]
Hey @ultrinnan , all yours ;)

**Comment by Cronus1007** [comment]
Hey @namitdoshi , I can do it Please assign me to this issue.

**Comment by ultrinnan** [comment]
@namitdoshi PR ready, please review

**Comment by ultrinnan** [comment]
@namitdoshi PR #6 is waiting :)

**Comment by namitdoshi** [comment]
thanks @ultrinnan
