### ISSUE TITLE
Enable the feature to upload images and save them in the database

### ISSUE THREAD

**Issue by namitdoshi** [namitdoshi/car-damage-detective-web#3]
Use 
The feature to upload pictures  is in the template file "templates/upload-pictures.html". You can make use of file "forms.py" to write the logic.

**Comment by sapnatomar** [comment]
I would like to take this issue.

**Comment by sapnatomar** [comment]
Hey @namitdoshi, I would like to take this issue.
Where do you want to direct the page on posting the pictures?

**Comment by namitdoshi** [comment]
Hey @sapnatomar, you can add a new page where the uploaded images would be displayed or display them on the same page as per your convenience. :)

**Comment by sapnatomar** [comment]
@namitdoshi I have created the pull request #9 . Please review it and suggest any corrections or changes, if needed.

**Comment by namitdoshi** [comment]
@sapnatomar Everything seems great, i'll be merging your PR. Good work 👍💯
Just one thing, I think you should refrain from adding the virtual environment to git repo.

**Comment by sapnatomar** [comment]
Oh, my bad! I will keep that in mind next time.
Should I fix it?

**Comment by namitdoshi** [comment]
No, let it be for now.
